### ISSUE TITLE
can't find WALLUP_DEBUG_URL and RELEASE URL

### ISSUE THREAD

**Issue by pavelsust** [DawnImpulse/wallup-android#5]
When building this application i am getting this error 
ERROR: Couldnotgetunknownproperty'WALLUP_DEBUG_URL'forBuildType_Decorated{
  name=debug,
  debuggable=true,
  testCoverageEnabled=false,
  jniDebuggable=false,
  pseudoLocalesEnabled=false,
  renderscriptDebuggable=false,
  renderscriptOptimLevel=3,
  minifyEnabled=false,
  zipAlignEnabled=true,
  signingConfig=SigningConfig_Decorated{
    name=debug,
    storeFile=/Users/anroid/.android/debug.keystore,
    storePassword=android,
    keyAlias=AndroidDebugKey,
    keyPassword=android,
    storeType=jks,
    v1SigningEnabled=true,
    v2SigningEnabled=true
  },
  embedMicroApp=false,
  mBuildConfigFields={
    
  },
  mResValues={
    
  },
  mProguardFiles=[
    
  ],
  mConsumerProguardFiles=[
    
  ],
  mManifestPlaceholders={
    
  }
}oftypecom.android.build.gradle.internal.dsl.BuildType.

how i can solve it and where i find the api and api key?

**Comment by DawnImpulse** [comment]
Hii,
You can remove the lines importing them from app/build.gradle file. After fixing this error the studio will also ask for google-services.json file. For that create a new project on firebase and grt the file from that since I cannot provide you with this file. Although If you are thinking to contribute to this project I will be more than happy to help you with that also. Send me mail on dawnimpulse@gmail.com & we will discuss :)
